export const de = {
  tabs: {
    home: 'Startseite',
    calendar: 'Kalender',
    groups: 'Gruppen',
    settings: 'Einstellungen',
  },
  home: {
    welcome: 'Willkommen bei Circle Todo',
    subtitle: 'Dein Produktivitätsbegleiter für die Verwaltung von Aufgaben und Organisation.',
    noTodos: '📋 Noch keine Aufgaben',
    noTodosSubtitle: 'Tippen Sie auf + um Ihre erste Aufgabe hinzuzufügen',
    completedTasks: 'Erledigte Aufgaben',
    pendingTasks: 'Ausstehende Aufgaben',
    overdueTask: '⚠️ Überfällig',
    dueToday: '📍 Heute fällig',
    dueTomorrow: '⏰ Morgen fällig',
    celebration: 'Großartig! 🎉',
  },
  todos: {
    addTodo: 'Aufgabe hinzufügen',
    addNew: 'Neue Aufgabe hinzufügen',
    editTodo: 'Aufgabe bearbeiten',
    title: 'Aufgabentitel',
    titlePlaceholder: 'Aufgabentitel eingeben...',
    placeholder: 'Aufgabentitel eingeben...',
    description: 'Beschreibung',
    descriptionPlaceholder: 'Beschreibung hinzufügen (optional)...',
    priority: 'Priorität',
    group: 'Gruppe',
    dueDate: 'Fälligkeitsdatum',
    setDueDate: 'Fälligkeitsdatum festlegen',
    removeDueDate: 'Fälligkeitsdatum entfernen',
    markComplete: 'Als erledigt markieren',
    markIncomplete: 'Als unerledigt markieren',
    deleteTask: 'Aufgabe löschen',
    confirmDelete: 'Sind Sie sicher, dass Sie diese Aufgabe löschen möchten?',
    deleteConfirm: 'Aufgabe löschen',
    noTasks: 'Noch keine Aufgaben',
    noCompleted: 'Keine erledigten Aufgaben',
    noPending: 'Keine ausstehenden Aufgaben',
    getStarted: 'Fügen Sie Ihre erste Aufgabe hinzu',
    search: 'Aufgaben suchen...',
    all: 'Alle',
    pending: 'Ausstehend',
    completed: 'Erledigt',
    allCompleted: 'Alle Aufgaben erledigt!',
  },
  priority: {
    low: 'Niedrig',
    medium: 'Mittel',
    high: 'Hoch',
  },
  calendar: {
    title: 'Kalenderansicht',
    subtitle: 'Planen Sie Ihre Aufgaben und verwalten Sie Fristen effektiv.',
    noTasksForDate: 'Keine Aufgaben für dieses Datum',
    tasksForDate: 'Aufgaben für',
    dueDate: 'Fälligkeitsdatum',
    selectDate: 'Datum auswählen',
  },
  groups: {
    title: 'Aufgabengruppen',
    subtitle: 'Organisieren Sie Ihre Aufgaben mit benutzerdefinierten Gruppen.',
    addGroup: 'Gruppe hinzufügen',
    editGroup: 'Gruppe bearbeiten',
    deleteGroup: 'Gruppe löschen',
    groupName: 'Gruppenname',
    groupNamePlaceholder: 'Gruppenname eingeben...',
    selectColor: 'Farbe auswählen',
    selectIcon: 'Symbol auswählen',
    confirmDeleteGroup: 'Sind Sie sicher? Dies entfernt die Gruppe von allen Aufgaben.',
    taskCount: 'Aufgabe',
    taskCountPlural: 'Aufgaben',
  },
  settings: {
    title: 'Einstellungen',
    subtitle: 'Passen Sie Ihre App-Erfahrung und Einstellungen an.',
    language: 'Sprache',
    theme: 'Design',
    light: 'Hell',
    dark: 'Dunkel',
    system: 'System',
    notifications: 'Benachrichtigungen',
    celebrationAnimations: 'Erfolgs-Animationen',
    about: 'Über',
    version: 'Version',
    clearData: 'Alle Daten löschen',
    confirmClearData: 'Dies löscht permanent alle Ihre Aufgaben und Gruppen. Diese Aktion kann nicht rückgängig gemacht werden.',
  },
  app: {
    title: 'Circle Todo',
    tagline: 'Dein Produktivitätsbegleiter',
  },
  common: {
    loading: 'Wird geladen...',
    error: 'Ein Fehler ist aufgetreten',
    retry: 'Wiederholen',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    save: 'Speichern',
    delete: 'Löschen',
    add: 'Hinzufügen',
    edit: 'Bearbeiten',
    done: 'Fertig',
    back: 'Zurück',
    close: 'Schließen',
    select: 'Auswählen',
    today: 'Heute',
    yesterday: 'Gestern',
    tomorrow: 'Morgen',
  },
} as const;