export const en = {
  tabs: {
    home: 'Home',
    calendar: 'Calendar',
    groups: 'Groups',
    settings: 'Settings',
  },
  home: {
    welcome: 'Welcome to Circle Todo',
    subtitle: 'Your productivity companion for managing tasks and staying organized.',
    noTodos: '📋 No tasks yet',
    noTodosSubtitle: 'Tap the + button to add your first task',
    completedTasks: 'Completed Tasks',
    pendingTasks: 'Pending Tasks',
    overdueTask: '⚠️ Overdue',
    dueToday: '📍 Due Today',
    dueTomorrow: '⏰ Due Tomorrow',
    celebration: 'Great job! 🎉',
  },
  todos: {
    addTodo: 'Add Task',
    addNew: 'Add New Task',
    editTodo: 'Edit Task',
    title: 'Task Title',
    titlePlaceholder: 'Enter task title...',
    placeholder: 'Enter task title...',
    description: 'Description',
    descriptionPlaceholder: 'Add description (optional)...',
    priority: 'Priority',
    group: 'Group',
    dueDate: 'Due Date',
    setDueDate: 'Set Due Date',
    removeDueDate: 'Remove Due Date',
    markComplete: 'Mark as Complete',
    markIncomplete: 'Mark as Incomplete',
    deleteTask: 'Delete Task',
    confirmDelete: 'Are you sure you want to delete this task?',
    deleteConfirm: 'Delete Task',
    noTasks: 'No tasks yet',
    noOpenTasks: 'No open tasks ... cheers! 🫰🏻',
    noCompleted: 'No completed tasks',
    completedTasksInfo: 'Completed tasks will appear here',
    noPending: 'No pending tasks',
    getStarted: 'Get started by adding your first task',
    search: 'Search tasks...',
    all: 'All',
    pending: 'Pending',
    completed: 'Completed',
    allCompleted: 'All tasks completed!',
  },
  priority: {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
  },
  calendar: {
    title: 'Calendar View',
    subtitle: 'Schedule your tasks and manage deadlines effectively.',
    noTasksForDate: 'No tasks for this date',
    tasksForDate: 'Tasks for',
    dueDate: 'Due Date',
    selectDate: 'Select Date',
  },
  groups: {
    title: 'Task Groups',
    subtitle: 'Organize your tasks with custom groups.',
    addGroup: 'Add Group',
    editGroup: 'Edit Group',
    deleteGroup: 'Delete Group',
    groupName: 'Group Name',
    groupNamePlaceholder: 'Enter group name...',
    selectColor: 'Select Color',
    selectIcon: 'Select Icon',
    confirmDeleteGroup: 'Are you sure? This will remove the group from all tasks.',
    taskCount: 'task',
    taskCountPlural: 'tasks',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Customize your app experience and preferences.',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    notifications: 'Notifications',
    celebrationAnimations: 'Celebration Animations',
    about: 'About',
    version: 'Version',
    clearData: 'Clear All Data',
    confirmClearData: 'This will permanently delete all your tasks and groups. This action cannot be undone.',
  },
  app: {
    title: 'Circle Todo',
    tagline: 'Your productivity companion',
  },
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    add: 'Add',
    edit: 'Edit',
    done: 'Done',
    back: 'Back',
    close: 'Close',
    select: 'Select',
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
  },
} as const;